version: '1'

services:
  node:
    container_name: node_container
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
    networks:
      - my_app

  postgres:
    container_name: postgres_container
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      my_app:
        ipv4_address: 172.18.0.10


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - my_app

networks:
  my_app:
    ipam:
      driver: bridge
      config:
        - subnet: "172.18.0.0/24"

volumes:
  postgres:
  pgadmin: